-- 01. Cria Database
CREATE DATABASE CESTA;

-- 02. Use Database
USE CESTA;

-- 03. Table Cliente
CREATE TABLE CLIENTE
( CODIGO INT AUTO_INCREMENT,
  NOME VARCHAR(50) UNIQUE,
  EMAIL VARCHAR(50) UNIQUE,
  TIPO ENUM('PF','PJ'),
  CPF VARCHAR(11) UNIQUE,
  SEXO ENUM('F','M'),
  CNPJ VARCHAR(15) UNIQUE,
  NOMEFANTASIA VARCHAR(75) UNIQUE,
  PRIMARY KEY(CODIGO));

CREATE TABLE CESTACOMPRA
( CODCESTA INT AUTO_INCREMENT,
  CODCLIENTE INT,
  VALORTOTAL NUMERIC(15,2),
  VALORDESCONTO NUMERIC(15,2),
  VALORLIQUIDO NUMERIC(15,2),
  QNTITENS INT,
  PRIMARY KEY(CODCESTA));


SELECT * FROM CESTACOMPRA;
INSERT INTO CESTACOMPRA
VALUES (1,1,0,0,0,0); 

SELECT CODIGO, NOME, CODCESTA, VALORTOTAL, 
CODITEM, PRODUTO, NOMEPRD,PRECO, QNT,
QNT*PRECO AS VALORBRUTO

FROM CLIENTE INNER JOIN CESTACOMPRA
              ON CODIGO = CODCLIENTE
INNER JOIN CESTAITEM
ON CODCESTA = 
CREATE  TABLE CESTAITEM
(CODITEM INT,
 CODCESTA INT,
 PRODUTO INT(3) ZEROFILL,
 QNT INT,
 VALORBRUTO NUMERIC(15,2),
 PRIMARY KEY(CODITEM));
 
 INSERT INTO CESTAITEM
 VALUES (101,1,3,10,0);

CREATE VIEW V_CESTAITEM
AS 
SELECT CODITEM, CODCESTA, PRODUTO, NOMEPRD,PRECO, QNT,
QNT*PRECO AS VALORBRUTO FROM CESTAITEM INNER JOIN PRODUTO
          ON PRODUTO = CODPRD;

SELECT * FROM V_CESTAITEM;

SELECT CODCESTA, SUM(VALORBRUTO) AS VALORTOTAL,
SUM(QNT) FROM V_CESTAITEM
GROUP BY CODCESTA;

-- 04. Insert Cliente  
INSERT INTO CLIENTE 
     VALUES (1,'CRISTIANO','cristiano@bol.com.br','PF',
             '12345678900','M',NULL,NULL);
             
INSERT INTO CLIENTE 
     VALUES (2,'INDUSTRIA TATY','taty@bol.com.br','PJ',
             NULL,NULL,'20150000120750','REFRIGERANTE PONCHIC');

SELECT * FROM CLIENTE;

1- cesta - adcionar itens 


CREATE TABLE PRODUTO
(CODPRD INT(3) ZEROFILL,
 NOMEPRD VARCHAR(50) NOT NULL,
 PRECO NUMERIC(15,2),
 PRIMARY KEY(CODPRD));
 
 SELECT * FROM PRODUTO;
 select now();
 INSERT INTO PRODUTO 
 VALUES (1,'TV 29 SAMSUNG',2750.99),
        (2,'MOTO G ONE',999.99),
        (3,'PENDRIVE 15G',25.99);

-- 01. Inserir Cliente (Codigo)
-- 02. Abrir c/Codigo do cliente (Codigo da Cesta)
-- 03. Adcionar itens com o codigo da cesta


DELIMITER //
CREATE FUNCTION FC_VALORBRUTO(QNT INT, PRD INT)
RETURNS NUMERIC(15,2)
BEGIN
	DECLARE VL_BRUTO NUMERIC(15,2);
    DECLARE VL_PRECO NUMERIC(15,2);
    
    SET VL_PRECO =  (SELECT PRECO 
                       FROM PRODUTO
					  WHERE CODPRD = PRD );
    SET VL_BRUTO = (QNT * VL_PRECO);
    RETURN VL_BRUTO;
END;