/*PIVOT OU PIVOTEAMENTO: TRANSFORMAR LINHAS(HORIZONTAL) EM COLUNAS(VERTICAL)*/

-- CRIANDO O BANCO:
CREATE DATABASE PIVO;

-- SETANDO O USODO BANCO:
USE PIVO;

-- CRIANDO TABELA VENDA:
CREATE TABLE VENDA(
COD INT(10) ZEROFILL AUTO_INCREMENT,
ANO VARCHAR(50),
MES VARCHAR (50),
VALOR_VENDA_ANO DECIMAL (15,3),
PRIMARY KEY (COD));

-- SELECIONANDO DADOS DA TABELA VENDA:
SELECT * FROM VENDA;

-- INSERINDO DADOS NA TABELA VENDA:
INSERT INTO VENDA (COD, MES, VALOR_VENDA_ANO) 
         VALUES (1,'JAN', 1.500),
				(2,'FEV', 1.400),
                (3,'MARC', 1.200),
                (4,'ABRIL', 1.450),
                (5,'MAIO', 3.500),
                (6,'JUN', 3.000),
                (7,'JULHO', 2.100),
                (8,'AGO', 2.200),
                (9,"SET", 1.890),
                (10,'OUT', 2.555),
                (11,'NOV', 3.250),
                (12,'DEZ', 1.170);

-- DESCRICAO DA TABELA VENDA:
DESC VENDA;

-- PIVOT ou PIVOTEAMENTO:
SELECT ANO,
			SUM(JAN) JAN, 
            SUM(FEV) FEV, 
            SUM(MARC) MARC, 
            SUM(ABRIL) ABRIL, 
            SUM(MAIO) MAIO, 
			SUM(JUN) JUN, 
            SUM(JULHO) JULHO, 
            SUM(AGO) AGO, 
            SUM("SET") "SET", 
            SUM("OUT") "OUT", 
            SUM(NOV) NOV, 
            SUM(DEZ) DEZ;
FROM (

SELECT ANO,
	   CASE WHEN MES=1 THEN VALOR_VENDA_ANO ELSE 0 END JAN,
       CASE WHEN MES=2 THEN VALOR_VENDA_ANO ELSE 0 END FEV,
       CASE WHEN MES=3 THEN VALOR_VENDA_ANO ELSE 0 END MARC,
       CASE WHEN MES=4 THEN VALOR_VENDA_ANO ELSE 0 END ABRIL,
       CASE WHEN MES=5 THEN VALOR_VENDA_ANO ELSE 0 END MAIO,
       CASE WHEN MES=6 THEN VALOR_VENDA_ANO ELSE 0 END JUN,
       CASE WHEN MES=7 THEN VALOR_VENDA_ANO ELSE 0 END JULHO,
       CASE WHEN MES=8 THEN VALOR_VENDA_ANO ELSE 0 END AGO,
       CASE WHEN MES=9 THEN VALOR_VENDA_ANO ELSE 0 END "SET",
       CASE WHEN MES=10 THEN VALOR_VENDA_ANO ELSE 0 END "OUT",
       CASE WHEN MES=11 THEN VALOR_VENDA_ANO ELSE 0 END NOV,
       CASE WHEN MES=12 THEN VALOR_VENDA_ANO ELSE 0 END DEZ,
  FROM VENDA
  GROUP BY ANO
);