DELIMITER //
CREATE FUNCTION REPETICAO (N1 INT, N2 INT)
RETURNS INT
BEGIN
	WHILE N1 < N2 DO
		SET N1 = N1+1;
    END WHILE;
    RETURN N1;
END;

DELIMITER //
CREATE FUNCTION REPETICAO2 (N1 INT, N2 INT)
RETURNS INT
BEGIN
    DECLARE VALOR INT DEFAULT 0;
	WHILE N1 < N2 DO
		SET VALOR = VALOR + N1;
        SET N1 = N1+1;
    END WHILE;
    RETURN VALOR;
END;

DELIMITER //
CREATE FUNCTION REPETICAO3 (N1 INT, N2 INT)
RETURNS INT
BEGIN
    DECLARE VALOR INT DEFAULT 0;
	WHILE N1 < N2 DO
        SET N1 = N1+1;
    END WHILE;
    RETURN N1;
END;