DELIMITER //
CREATE FUNCTION FC_MENSAGEM (FRASE VARCHAR(100)) 
RETURNS CHAR(250)
RETURN CONCAT( ' Olá ', FRASE, ' Seja Bem Vindo a Programação em SQL !!! ' );

DELIMITER // 
CREATE FUNCTION FC_CALCULA_CUBO( CUBO INT ) 
RETURNS INT 
BEGIN 
	SET CUBO = (CUBO*CUBO*CUBO); 
     RETURN (CUBO); 
END;


SELECT CODIGO, FC_CALCULA_CUBO(CODIGO) AS FUNCAO_CUBO, 
               FC_MENSAGEM(NOME) AS FUNCAO_MENSAGEM
   FROM CLIENTE;


DELIMITER // 
CREATE FUNCTION FC_IF_ELSE( VALOR INT, CLIENTE VARCHAR(50) )
RETURNS VARCHAR(300) 
BEGIN 
	
DECLARE N1 INT DEFAULT 10; 
DECLARE N2 INT DEFAULT 20;
DECLARE N3, N4 INT;
DECLARE MSG VARCHAR(300);    
    	IF ( VALOR%2 = 0 ) THEN -- FUNCAO MODE% PEGA O RESTO DA DIVISÃO.
		SET N3 = ( N1 * VALOR);
        SET MSG = CONCAT('O código do Cliente ', CLIENTE, ' é um valor PAR multiplicado pela  Variável N1 é = ', N3);
	ELSE 
		SET N4 = ( N2 * VALOR);
SET MSG = CONCAT('O código do Cliente ', CLIENTE, ' é um valor IMPAR multiplicado pela    Variável N2 é = ', N4);
	END IF;
    
	RETURN MSG; 

     END;




