-- 05 FUNÇÃO REAJUSTE SALARIAL:

DELIMITER //
CREATE FUNCTION FC_REAJUSTE_SALARIO(SALARIO NUMERIC(15,2),COD INT, FUNCAO VARCHAR(1))
RETURNS NUMERIC (15,2)
BEGIN
DECLARE RESULT NUMERIC(15,2);
	 IF (FUNCAO = 'A') THEN
		SET RESULT = (SALARIO + (SALARIO * 0.10 + 1.90));
	 ELSEIF (FUNCAO = 'B') THEN
		SET RESULT = (SALARIO + (SALARIO * 0.10 + 1.70));
	 ELSEIF (FUNCAO = 'C') THEN
		SET RESULT = (SALARIO + (SALARIO * 0.10 + 1.50));
	 ELSE 
		SET RESULT = 0;
	END IF;
RETURN RESULT;
END;
