DELIMITER //
CREATE PROCEDURE SP_loop_WHILE (IN CONTADOR_1 INT, CONTADOR_2 INT)
BEGIN
WHILE CONTADOR_1 <= CONTADOR_2 DO
INSERT INTO CLIENTE (NOME,DATACADASTRO) VALUES (CONTADOR_1, NOW());
SET CONTADOR_1 = (CONTADOR_1 + 1);
END WHILE;
END